Creado modelo Talk
PyBAQ/temii pull request #209
Opened 2023-08-13 00:39 UTC by Scot3004

Work in progress
Se creo el modelo para charla, lenguaje y nivel de la charla
Está pendiente la creación de los escenarios de prueba y los respectivos tests

2023-08-22 18:57 UTC, pyjavo commented on temii/talks/models.py
> +class TalkLanguage(models.Model):
Si solo van a haber 2 opciones de lenguaje de la charla (español e inglés). Sugiero colocar las opciones en el mismo modelo Talk y no crear una tabla nueva en la base de datos solo para estos 2 valores.

Ejemplo
https://docs.djangoproject.com/en/4.2/ref/models/fields/#choices

```python
from django.db import models


class Student(models.Model):
    FRESHMAN = "FR"
    SOPHOMORE = "SO"
    JUNIOR = "JR"
    SENIOR = "SR"
    GRADUATE = "GR"
    YEAR_IN_SCHOOL_CHOICES = [
        (FRESHMAN, "Freshman"),
        (SOPHOMORE, "Sophomore"),
        (JUNIOR, "Junior"),
        (SENIOR, "Senior"),
        (GRADUATE, "Graduate"),
    ]
    year_in_school = models.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=FRESHMAN,
    )

    def is_upperclass(self):
        return self.year_in_school in {self.JUNIOR, self.SENIOR}
```

2023-08-22 18:58 UTC, pyjavo commented on temii/talks/models.py
> +class TalkLevel(models.Model):
Creo que solo hay 3 niveles:
- Beginner
- Intermediate
- Advance

2023-08-23 14:05 UTC, Scot3004 commented on temii/talks/models.py
> +class TalkLevel(models.Model):
Te refieres a algo como esto?
```python
BEGINNER = 1
INTERMEDIATE = 2
AVANCED = 3
LEVEL_CHOICES  = [
    (BEGINNER, "Principiante"),
    (INTERMEDIATE, "Intermedio"),
    (AVANCED, "Avanzado"),
]
```

2023-09-13 17:19 UTC, pyjavo requested changes
¡Excelente! 💪💪💪 Estamos cada vez más cerca. Este PR está relacionado con el issue #140 

Unas sugerencias:

1. Falta el campo de **Mes(es) de la charla** para que el ponente sugiera su fecha preferida para hablar (ver formulario de Google como guía).
2. Falta el campo **modalidad de la charla** para saber si la charla será "Presencial en Barranquilla" o "Virtual (estoy fuera de Barranquilla)"
3. Resetear las **migraciones** del Modelo Talk para que solo exista `0001_initial.py` en este PR
Tal vez conviene ver https://simpleisbetterthancomplex.com/tutorial/2016/07/26/how-to-reset-migrations.html

2023-09-19 21:06 UTC, Scot3004 commented
Para los meses creo que sería mucho mejor postular a eventos,  (que en este contexto sería lo mismo que meses)

2023-09-19 22:28 UTC, pyjavo commented
@Scot3004 Podrías explicarme, ¿a qué te refieres con **postular a eventos**?

2023-09-19 22:35 UTC, Scot3004 commented
Es que aparezca un listado de eventos y puedas escoger en que evento te gustaría que aparezca
En vez de asociarlo al mes a los posibles eventos

2023-10-05 03:00 UTC, pyjavo commented
@Scot3004 pero creo que cuando el ponente aplica, aún no hay un evento o eventos disponibles. Esa persona solo sabe de antemano que mes o meses de su agenda personal puede disponer para su **propuesta de charla**.

Pienso que el paso a paso inicial es el siguiente (disculpa que no es un diagrama de flujo):

1. Persona aplica con una nueva charla
2. La charla entra a la lista de posibles charlas
3. El admin escoge una o varias charlas para un futuro evento
4. **Se crea el evento** con fecha, hora, lugar y charla(s) elegida(s).
5. Se promociona el evento en redes sociales.
6. Una vez terminada la charla, se recopilan sus recursos para publicar en el sitio web. Ej: URL de youtube, diapositivas, URL del repositorio o se sube a PyBAQ/Notebooks. Todo dependiendo de cada caso.

¿Qué opinas?

2023-10-05 13:57 UTC, Scot3004 commented
Ok, ¿Que tipo de datos le ponemos a los meses?, CharField de 300?

2023-10-06 15:06 UTC, pyjavo commented
@Scot3004 si vamos a guardar caracteres de texto con los nombres de los meses, sea "enero", "febrero", "marzo", etc, entonces, según mis cálculos, *septiembre* es el mes con mayor número de caracteres. Tiene 10 caracteres (le siguen "noviembre" y "diciembre" con 9).
Podríamos hacer un Charfield(20) para dejar un buffer de 10 caracteres de más, solo por si acaso jeje.

¿Qué opinas?

2023-10-06 16:03 UTC, Scot3004 commented
Al menos 100 pa que pueda meter 5 meses jeje

2023-10-06 16:04 UTC, Scot3004 commented
Al menos 100 pa que pueda meter 9 meses (más o menos si los coloca en formato largo separado con espacios)

2023-10-06 22:22 UTC, pyjavo commented
@Scot3004 tienes razón. No había caído en cuenta de ese escenario

2023-10-07 18:33 UTC, Scot3004 commented on temii/talks/models.py
> +    class InPerson(models.TextChoices):
Deberia ser IntegerChoices

2023-10-07 18:40 UTC, Scot3004 commented
![image](https://github.com/PyBAQ/temii/assets/1175402/48aa2446-8668-4848-bb60-c56b555ebaef)
Listo, Por alli veo unos inconvenientes con la localización, no se por que suceden, pero creo que ya este PR esta lo suficiente grande, y es mas cuestion de forma que de fondo

2023-10-07 18:47 UTC, Scot3004 commented
Encontre la causa python manage.py compilemessages

2023-10-07 18:48 UTC, Scot3004 commented
![image](https://github.com/PyBAQ/temii/assets/1175402/5c601d1c-2dee-4058-9621-924cb69b6bad)

2023-10-08 21:36 UTC, Scot3004 commented
Ya se aplicaron los 3 puntos
Se creo un campo meses con capacidad de 100 caracteres
La modalidad de la charla se aborda en el campo "Presencialidad" que tiene 2 opciones "En sitio" y "Virtual"
Presencialidad en Sitio, es para cuando la charla va a ser presencial en el lugar del evento,  igual el hecho que sea virtual es tambien estar presente en la reunión solo que de forma virtual
Los flujos de charlas, lo abordaria mejor en otro issue, la verdad ya este esta lo suficientemente grande, y eso que la gestión de la charla se hace en el admin
No se abordo la creación del formulario de charla en el front office, para permitir que eso se aborde en un ticket futuro, solo lo que si o si requeria tener en el modelo

2023-10-10 00:29 UTC, pyjavo approved these changes
De acuerdo. Lo restante lo podemos abordar en otro PR. ¡Buen trabajo!

2023-10-10 00:30 UTC, merged