feat: Formulario y vista para proponer una nueva charla
PyBAQ/temii pull request #217
Opened 2023-10-22 00:11 UTC by pyjavo

# Pull request

Relacionado con #149

## Observaciones

Luego de que el usuario propone una nueva charla, redirijo a una página de agradecimiento. En la lógica del formulario de google, solo el o los admins pueden ver el listado de charlas propuestas

2023-10-22 00:12 UTC, pyjavo commented
WIP: Unit tests

2023-10-22 05:54 UTC, Scot3004 reviewed
![image](https://github.com/PyBAQ/temii/assets/1175402/97ddc252-6bc2-490e-bc9e-88bed19c0047)

Me gusta mucho como se ve, me avisas cuando este listo para revisión

2023-10-27 23:57 UTC, pyjavo commented
Listo. Agregue iternacionalizacion también

2023-10-30 09:19 UTC, Scot3004 requested changes
Se ve bien el formulario

![image](https://github.com/PyBAQ/temii/assets/1175402/05761196-7bc2-4099-918d-cb235e748ed0)

Sin embargo al intentar guardar los registros, aun luego de hacer migraciones, me aparece este error

![image](https://github.com/PyBAQ/temii/assets/1175402/2e67e6f8-50f6-479a-ae14-12c915824167)

Se solicitan los siguientes cambios:
- Crear migraciones, y que se pueda guardar la charla
- Traducir los mensajes faltantes, que sirven como información de ayuda para diligenciar los campos

2023-10-30 09:19 UTC, Scot3004 commented on temii/talks/models.py
> +    timezone = models.CharField(
Al cambiar los modelos se requieren crear migraciones, por favor, crealas

2023-10-30 09:19 UTC, Scot3004 commented on locale/es/LC_MESSAGES/django.po
> +"Timezone of the place you are located. E.g., Colombia (UTC-5), Argentina or "
Creo que seria bueno traducir este mensaje

2023-10-30 09:19 UTC, Scot3004 commented on locale/es/LC_MESSAGES/django.po
> +"Timezone of the place you are located. E.g., Colombia (UTC-5), Argentina or "
![image](https://github.com/PyBAQ/temii/assets/1175402/275d94a4-5d0d-499c-a241-9aaa93245079)

2023-10-31 02:20 UTC, pyjavo commented
Listo. Agregue las migraciones y las nuevas traducciones :)

2023-11-01 01:43 UTC, Scot3004 requested changes
Un pequeño typo en una de las traducciones, pero ya casi

2023-11-01 02:29 UTC, pyjavo commented on locale/es/LC_MESSAGES/django.po
> +msgstr "ona horaria del lugar donde se encuentra. Por ejemplo,"
jeje ups. Ya lo corregí

2023-11-01 17:28 UTC, Scot3004 approved these changes
Excelente 👯

2023-11-01 17:29 UTC, merged